title: QT-PyQt-PySide-Custom-Widgets Documentation
logo: "/logo.png"
email: spinncompany@gmail.com
description: >- 
  Documentation for QT-PyQt-PySide-Custom-Widgets by Khamisi Kibet
baseurl: "/" 
url: "" 
github_username: https://github.com/KhamisiKibet

remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

aux_links:
  "QT-PyQt-PySide-Custom-Widgets in Github":
    - "https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets"
  "YouTube":
    - "https://youtube.com/spinntv"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2024"
