plugins:
  - jekyll-default-layout
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

title: QT-PyQt-PySide-Custom-Widgets
logo: "/images/logo.png"
email: spinncompany@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  Awesome custom widgets made for QT Desktop Applications. Simplify your UI development process. These widgets can be used in QT Designer then imported to PySide code.
  By Khamisi Kibet
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  https://github.com/KhamisiKibet

# Build settings
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

aux_links:
  "T-PyQt-PySide-Custom-Widgets in Github":
    - "https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2023"

aux_links:
  Template Repository: https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets
