name: Build Jekyll Site

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7  # Adjust the Ruby version as needed

      - name: Install Bundler
        run: gem install bundler

      - name: Install Dependencies
        run: bundle install --with jekyll_plugins

      - name: Build Jekyll Site
        run: bundle exec jekyll build
